/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(test_block.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1a7b5c00bee4c94c407a73ff6e0403f3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/test/test_block.h>
// pydoc.h is automatically generated in the build directory
#include <test_block_pydoc.h>

void bind_test_block(py::module& m)
{

    using test_block = ::gr::test::test_block;


    py::class_<test_block,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<test_block>>(m, "test_block", D(test_block))

        .def(py::init(&test_block::make), D(test_block, make))


        ;
}
